### ISSUE TITLE
Add execute-time JL extension

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/infra#114]
To know when and how long a cell was run use https://github.com/deshaw/jupyterlab-execute-time

**Comment by Peter9192** [comment]
Quite nice indeed. Can we clarify the usecase for this? Mostly provenance, I guess? For runtime/profiling you can also use ipython magic.

**Comment by sverhoeven** [comment]
Indeed having time shown always makes the UI even more busy.
