### ISSUE TITLE
Dont create single student1, but multiple users

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/infra#13]
At the moment a single user called `student1` is created. JupyterHub supports multiple users and we want to do workshops where each user has his/her own account.

Instead of using `student` prefix choose something more neutral like `user`.

**Comment by sverhoeven** [comment]
Accounts are currently configured [vars.yml](https://github.com/eWaterCycle/infra/blob/master/launcher/vars.yml.template) and are created by running a [Ansible playbook](https://github.com/eWaterCycle/infra/tree/master/launcher).

**Comment by bpmweel** [comment]
Looks good. Only thing I found confusing was that the jupyter role hub.yml states the task as:
"- name: Allow posix_users to use docker" while this is the command that actually creates users

**Comment by sverhoeven** [comment]
Changed name to `Create users for Jupyter Hub with Docker permission` in fe731ac466fa3c4432b32f03a1b4853ca0fbef4b

**Comment by sverhoeven** [comment]
Multiple users are now available on Jupyter Hub server.
