### ISSUE TITLE
Guests accounts failing on demo machine

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/infra#134]
Guest accounts no longer seem to work on the demo machine.

**Comment by sverhoeven** [comment]
I was able to login via JupyterHub. 

Login in via ssh fails as expected because login with password is disabled in the ssh server.

**Comment by sverhoeven** [comment]
The hashed password in the /etc/shadow and ansible playbook has following format `$<rounds>$<salt>$<hashed password>`.

When I rehash the password with `mkpasswd  --method=sha-512 <cleartext password> <salt>`. 
I get the same hashed password back for the last user in the playbook, but all other users generate a different hash. 

So we will need to regenerate the hashes again and make sure logins works.

**Comment by sverhoeven** [comment]
Guest accounts have been regenerated. 

Each guest account has a changed password.
