### ISSUE TITLE
Dead link to example notebooks

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/infra#144]
See https://github.com/eWaterCycle/ewatercycle/issues/366. We removed the example notebooks folder in the ewatercycle repo. However, that folder is linked on the terria landing page, to go to "example notebooks". We should bring it back or find another way to provide examples to new users via the platform.

**Comment by sverhoeven** [comment]
The link is code up at https://github.com/eWaterCycle/TerriaMap/blob/ewatercycle-v8/lib/Views/UserInterface.jsx#L33-L54
