### ISSUE TITLE
Python version pinned to 3.10.0 in environment.yml

### ISSUE THREAD

**Issue by BSchilperoort** [eWaterCycle/infra#151]
By setting the python version to `==3.10`, 3.10.0 is installed.
If this is changed to `=3.10` the latest patch (3.10.*) will be installed, which contains bug & security fixes.

https://github.com/eWaterCycle/infra/blob/86a3ee36616712ff861d6af704afe9cab2c7a649/roles/ewatercycle/templates/environment.yml.j2#L8

Was this intentional? @sverhoeven

**Comment by sverhoeven** [comment]
No I think we wanted to just to pin the major version. We could make the pin more loose.
