### ISSUE TITLE
Use hostnames inside ewatercycle.org domain for machines

### ISSUE THREAD

**Issue by nielsdrost** [eWaterCycle/infra#16]
The system should use one or more hostnames inside the ewatercycle.org domain, instead of the surf-hosted domain we use now. This is mostly important for the "entrypoint" terriajs explorer, the hostname of the jupyter hub and/or notebook servers are of less importance.

Perhaps explore.ewatercycle.org for the explorer, and lab.ewatercycle.org for the jupyter environment?

**Comment by sverhoeven** [comment]
* lab.ewatercylce.org - entry page to select other servers
* explore.ewatercylce.org - terriajs with models and datasets and launcher
* jupyter.ewatercylce.org - jupyterhub 
* analytics.ewatercylce.org -
* experiments.ewatercylce.org - cylc web interface

**Comment by sverhoeven** [comment]
@nielsdrost can you make the following cname entries in the ewatercylcle.org domain?
* lab.ewatercylce.org -> lab.ewatercycle2-nlesc.surf-hosted.nl:
* explore.ewatercylce.org -> explore.ewatercycle2-nlesc.surf-hosted.nl
* jupyter.ewatercylce.org -> jupyter.ewatercycle2-nlesc.surf-hosted.nl
* analytics.ewatercylce.org ->analytics.ewatercycle2-nlesc.surf-hosted.nl
* experiments.ewatercylce.org ->experiments.ewatercycle2-nlesc.surf-hosted.nl

**Comment by nielsdrost** [comment]
DNS entries made, including:

* forecast.ewatercylce.org -> forecast.ewatercycle2-nlesc.surf-hosted.nl

I also *nuked* the Amazon EC2 forecast machine.

**Comment by nielsdrost** [comment]
@sverhoeven I think this is done now, right?

@bpmweel can you review?

**Comment by sverhoeven** [comment]
Yes, cloud servers are using *.ewatercycle.org domain names. It is part of PR #22

**Comment by sverhoeven** [comment]
Done
