### ISSUE TITLE
Use conda lock

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/infra#164]
Sometime the creation of a new Virtual Machine will fail due conda dependency conflicts/problems. This can be lessened by using conda-lock to install a known working pinned set of dependencies.

See https://github.com/eWaterCycle/ewatercycle/pull/442

**Comment by Peter9192** [comment]
also see https://github.com/eWaterCycle/ewatercycle/issues/357

**Comment by sverhoeven** [comment]
The [ewatercycle conda lock file](https://github.com/eWaterCycle/ewatercycle/blob/main/conda-lock.yml) and [infra conda env file](https://github.com/eWaterCycle/infra/blob/main/roles/ewatercycle/templates/environment.yml.j2) need to merged somehow.

We could first run conda-lock and then update env with  a trimmed down version of the environment.yml.j2.
