### ISSUE TITLE
Make research drive available on Jupyter server

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/infra#20]
The experiments (cylc) and forecast server use rclone and cron jobs to sync data to/from researchdrive.

Inside a notebook it would be nice to access this forecast data aswell.

**Comment by sverhoeven** [comment]
This could be implemented with either:
* rclone mount, reusing rclone role, see https://rclone.org/commands/rclone_mount/
* davfs2, https://doc.owncloud.org/server/8.2/user_manual/files/access_webdav.html#creating-webdav-mounts-on-the-linux-command-line

**Comment by sverhoeven** [comment]
Now can be done using https://servicedesk.surfsara.nl/wiki/display/WIKI/Connect+Research+Drive

**Comment by Peter9192** [comment]
Is this issue still relevant?

**Comment by sverhoeven** [comment]
For accessing forecast as wanted in this issue we can now use dCache mount.

To have home dir survive recreation of vm it should either be put on a storage item or on a remote filesystem like research drive.
So it depends if and how we want to make homedirs persistent.
