### ISSUE TITLE
Landing page intro

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/infra#23]
Edit https://github.com/eWaterCycle/infra/blob/lab/roles/labstart/templates/index.html.j2

**Comment by nielsdrost** [comment]
Is it just me, or do the buttons on the landing page not work at the moment?

**Comment by sverhoeven** [comment]
Doh, fixed it

**Comment by nielsdrost** [comment]
Working on content and layout of this page now

**Comment by sverhoeven** [comment]
Page now has intro, logos and nicer layout
