### ISSUE TITLE
Automatic renewal of certificates

### ISSUE THREAD

**Issue by sverhoeven** [eWaterCycle/infra#30]
The machines at https://lab.ewatercycle.org/ have been running far longer than expected. Causing their let's encrypt certificates to expire on 10 June 2019. They have to be renewed.

**Comment by sverhoeven** [comment]
The current ansible playbook first installs a cert and then install a web server. This makes it impossible for the certbot to renew. 
For example
```bash
journalctl -u certbot.service
...
May 23 09:43:03 lab.ewatercycle.org certbot[14663]: Attempting to renew cert (lab.ewatercycle2-nlesc.surf-hosted.nl) from /etc/letsencrypt/renewal/lab.ewatercycle2-nlesc.surf-hosted.nl.conf produced an unexpected error: Problem binding t
May 23 09:43:04 lab.ewatercycle.org certbot[14663]: Attempting to renew cert (lab.ewatercycle.org) from /etc/letsencrypt/renewal/lab.ewatercycle.org.conf produced an unexpected error: Problem binding to port 80: Could not bind to IPv4 or
May 23 09:43:04 lab.ewatercycle.org certbot[14663]: All renewal attempts failed. The following certs could not be renewed:
May 23 09:43:04 lab.ewatercycle.org certbot[14663]:   /etc/letsencrypt/live/lab.ewatercycle2-nlesc.surf-hosted.nl/fullchain.pem (failure)
May 23 09:43:04 lab.ewatercycle.org certbot[14663]:   /etc/letsencrypt/live/lab.ewatercycle.org/fullchain.pem (failure)
May 23 09:43:04 lab.ewatercycle.org certbot[14663]: 2 renew failure(s), 0 parse failure(s)
May 23 09:43:04 lab.ewatercycle.org systemd[1]: certbot.service: Main process exited, code=exited, status=1/FAILURE
May 23 09:43:04 lab.ewatercycle.org systemd[1]: certbot.service: Failed with result 'exit-code'.
May 23 09:43:04 lab.ewatercycle.org systemd[1]: Failed to start Certbot.
```

Can be solved in 2 ways:
1. Temporary stop service using port 80 using pre/post hooks in certbot config
2. Configure certbot and service using port 80 to proxy challenge

Only temporary stop services which can be interrupted without causing harm. Killing a running notebook would not be appreciated.

**Comment by sverhoeven** [comment]
When the renewal has been implemented it would be nice if the new certs could be backed up running a backup command using a playbook with a tag.

**Comment by sverhoeven** [comment]
For now the certificates have been renewed manually with:
```
# lab
certbot renew --webroot -w /var/www/html && service nginx reload
# explore
service nginx stop && certbot renew && service nginx start
# jupyter, cert was already renewed, but jupyterhub was still using old cert
service jupyterhub restart
# experiments
service nginx stop && certbot renew && service nginx start
# forecast, cert was already renewed, but jupyterhub was still using old cert
service forecast-web restart
```

The new certs where backed up with
```
rsync --rsync-path="sudo rsync" -a <hostname>:/etc/letsencrypt/ letsencrypt/<hostname>/
```

**Comment by sverhoeven** [comment]
@nielsdrost can this be added to the team backlog?

**Comment by sverhoeven** [comment]
Certs where renewed manually again

**Comment by sverhoeven** [comment]
Certs where renewed manually again on 22 Oct 2019

**Comment by nielsdrost** [comment]
@sverhoeven the certificates are in need of a manual refresh, thanks!

**Comment by nielsdrost** [comment]
Also, added it to the team backlog.

**Comment by sverhoeven** [comment]
Certs updated:
- lab, expires 18-2-2020
- explore and experiments and forecast, expires 7-4-2020
- jupyter, expires 6-4-2020
