### ISSUE TITLE
shapely 1.6.4 incompatible with some shapefiles needed for comparison

### ISSUE THREAD

**Issue by bouweandela** [eWaterCycle/infra#43]
Apparently shapely 1.6.4 is incompatible with this shapefile:
HYPE_Shapefiles/Meuse_HYPE/Meuse_HYPE.shp from https://github.com/eWaterCycle/recipes_auxiliary_datasets/blob/master/hype/HYPE_Shapefiles.tar.gz
but it works fine with shapely 1.7.0

For now I will just `pip install --upgrade shapely` in the ESMValTool conda environment on the jupyter machine. Hopefully this issue will be automatically solved next time we install ESMValTool.

This issue was reporeted by @ipelupessy

**Comment by sverhoeven** [comment]
On SRC VM shapely 1.7.1 is installed
