### ISSUE TITLE
TASK [ewatercycle : Install eWaterCycle conda environment] failed

### ISSUE THREAD

**Issue by SarahAlidoost** [eWaterCycle/infra#66]
Using the PR #63, this task failed because of dependencies conflicts, please see attached the log file. 
[ansible_log.txt](https://github.com/eWaterCycle/infra/files/5022179/ansible_log.txt)

**Comment by Peter9192** [comment]
Holy shit, that's a lot of conflicts. I can hardly imagine that's caused by those few changes, except maybe the ESMValTool package. Can you try to revert that one and see if it solves the conflicts?

**Comment by sverhoeven** [comment]
At the moment we are using a [conda env file](https://github.com/eWaterCycle/infra/blob/main/roles/ewatercycle/files/environment.yml) which does not pin a lot of versions and seems to work when installed with mamba.

Does it work with current setup?

**Comment by sverhoeven** [comment]
Was solved for machined provisioned on 1 Jan 2022.
