### ISSUE TITLE
Add extra_facets_dir to ESMValTool config-user

### ISSUE THREAD

**Issue by Peter9192** [eWaterCycle/infra#83]
See https://github.com/ESMValGroup/ESMValCore/issues/1232

Can we also update the current users' ESMValTool config on the Jupyter machine?

**Comment by sverhoeven** [comment]
Added in https://github.com/eWaterCycle/infra/commit/1b4ab5348549dfb0ac9e2a47a2220614520ddb46

Also in users of demo machines
